
name: CICD
on:
  
  push:
jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: '18'

      
      - name: Install Newman
        run: npm install -g newman

      - name: Run Newman for Postman Testcases
        run: run newman postman_testcases\Books.postman_collection.json -e postman_testcases\test.postman_environment.json
